name: ci

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        tomcat: ["8.5.55", "8.5.56", "8.5.57", "8.5.58", "8.5.59", "8.5.60", "8.5.61", "8.5.63", "8.5.64", "8.5.65", "8.5.66", "8.5.68", "8.5.69", "8.5.70", "8.5.71", "8.5.72", "8.5.73"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dyrnq/tomcat:${{ matrix.tomcat }}${{ matrix.tomcat == '8.5.73' && ',dyrnq/tomcat:latest' || ''}}
          build-args: |
            TOMCAT_VERSION=${{ matrix.tomcat }}